version: 2

sources:
  - name: raw
    schema: raw
    tables:
      - name: orders

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null